### ISSUE TITLE
iOS not running

### ISSUE THREAD

**Issue by anthonycmain** [react-everywhere/re-start#30]
I've just tried running a fresh installation from the README. The web version seems to run up fine, but the iOS version has AppRegistry issues

<img width="284" alt="screen shot 2017-09-30 at 10 09 04" src="https://user-images.githubusercontent.com/950131/31044444-6ddeaa4e-a5c7-11e7-9ba4-23db35a116b0.png">

**Comment by hgonzalez94** [comment]
same :(

**Comment by amoghbanta** [comment]
can you please share how your package.json looks like, that might help figure out the issue.

**Comment by anthonycmain** [comment]
Here's a copy of mine, I've made no changes to it other than from the create scripts

[package.json.txt](https://github.com/react-everywhere/re-start/files/1349541/package.json.txt)

**Comment by anthonycmain** [comment]
Sorry previous upload was wrong.

Here is mine, I made no further changes to it other than the Create Scripts

[package.json.txt](https://github.com/react-everywhere/re-start/files/1349551/package.json.txt)

**Comment by Evaske** [comment]
Had the same issue. I started a project with the folder name EveryWhereTest. For some reason, it called the component in index.ios.js only "everywhere" so that it was complaining that EveryWhereTest wasn't registered.

Have a look in your index.ios.js and make sure that the three locations in your case say TDAppFramework.

```
export default class TDAppFramework extends Component {
    render() {
        return  <App/>;
    }
}
AppRegistry.registerComponent('TDAppFramework', () => TDAppFramework);
```

I suspect it has probably done it as something like tdapp instead.

**Comment by amoghbanta** [comment]
This should be fixed with the latest template.
```
react-native init projectName --template re-start
cd projectName
node scripts/additionalDependencies.js
```
